#!/usr/bin/env python3
"""
logos_compile.py — Logos → C transpiler
Usage: python logos_compile.py logos_sort.lg > logos_sort_gen.c

Handles the subset of Logos syntax used in logos_sort.lg:
  - Types: i64 u64 u128 usize int bool → int64_t uint64_t __uint128_t size_t int int
  - Consts, structs, fns (static by default, pub = exported)
  - let/var declarations with optional type annotation
  - for i in lo ..= hi / lo .. hi / 0..N
  - while / loop (→ while(1)) / if-else
  - tail (lo, hi, depth) = (...) → assignment + continue (TCO loop body)
  - swap(x, y) → swap macro
  - swap_elem(a, i, j) → swap64 call
  - stack_alloc[T; n] → VLA declaration (with #include guard)
  - zero_fill(buf, n) → memset(buf, 0, n*sizeof(*buf))
  - ilog2(n) → (int)(log2((double)(n)))
  - wrapping_add / wrapping_mul → C wrapping arithmetic (just +/*)
  - __platform_entropy_impl() → #ifdef block
  - Tuple returns (a, b) → out-pointer pattern

Limitations (by design — not a full parser):
  - Single-statement expressions only (no multi-line expressions)
  - No generics, no lifetimes, no closures
  - impl blocks are not supported (use free functions)
  - Comments use // (same as C, passed through)
"""

import re
import sys

# ── Type map ──────────────────────────────────────────────────────────────────
TYPES = {
    "i64":    "int64_t",
    "u64":    "uint64_t",
    "u128":   "__uint128_t",
    "usize":  "size_t",
    "u8":     "uint8_t",
    "u32":    "uint32_t",
    "int":    "int",
    "bool":   "int",
    "f64":    "double",
    "*mut i64":  "int64_t*",
    "*mut u64":  "uint64_t*",
    "*mut usize":"size_t*",
    "[i64; 64]": "int64_t[64]",
}

def map_type(t):
    t = t.strip()
    return TYPES.get(t, t)

# ── Header emitted once ───────────────────────────────────────────────────────
HEADER = """/* Auto-generated by logos_compile.py from logos_sort.lg — DO NOT EDIT */
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdatomic.h>

#ifdef _WIN32
#  define WIN32_LEAN_AND_MEAN
#  include <windows.h>
static uint64_t __platform_entropy_impl(void) {
    LARGE_INTEGER pc; QueryPerformanceCounter(&pc);
    return (uint64_t)pc.QuadPart ^ (uint64_t)(uintptr_t)&pc;
}
#else
#  include <time.h>
#  if defined(__linux__) || defined(__APPLE__)
#    include <sys/random.h>
#  endif
static uint64_t __platform_entropy_impl(void) {
    uint64_t v = 0;
    if (getentropy(&v, sizeof(v)) == 0) return v ^ (uint64_t)(uintptr_t)&v;
    struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return (uint64_t)ts.tv_nsec ^ ((uint64_t)ts.tv_sec << 32)
           ^ (uint64_t)(uintptr_t)&ts;
}
#endif

#define SWAP_VALS(T, a, b) do { T _t = (a); (a) = (b); (b) = _t; } while(0)
#define COUNT_STACK_MAX (1u << 16)
"""

# ── Regex helpers ─────────────────────────────────────────────────────────────

def tr_type_annotation(s):
    """Replace Logos type annotations with C types."""
    for logos, c in TYPES.items():
        s = s.replace(f": {logos}", f" /*:{logos}*/").replace(logos, c)
    return s

def tr_for_range(line, indent):
    """Convert Logos for-range syntax to C for loop."""
    # for i in lo ..= hi
    m = re.match(r'for (\w+) in (.+?) \.\.= (.+?) \{', line.strip())
    if m:
        v, lo, hi = m.groups()
        return f"{indent}for (size_t {v} = {lo}; {v} <= {hi}; {v}++) {{"
    # for i in lo .. hi
    m = re.match(r'for (\w+) in (.+?) \.\. (.+?) \{', line.strip())
    if m:
        v, lo, hi = m.groups()
        return f"{indent}for (size_t {v} = {lo}; {v} < {hi}; {v}++) {{"
    return None

def tr_let_var(line, indent):
    """Convert let/var declarations."""
    # let x: T = expr  OR  var x: T = expr
    m = re.match(r'(let|var) (\w+): (.+?) = (.+)', line.strip())
    if m:
        _, name, typ, expr = m.groups()
        ctype = map_type(typ)
        expr = tr_expr(expr)
        return f"{indent}{ctype} {name} = {expr};"
    # let x: [T; N]  (array, no initializer)
    m = re.match(r'(let|var) (\w+): \[(.+?); (\d+)\]$', line.strip())
    if m:
        _, name, typ, sz = m.groups()
        ctype = map_type(typ)
        return f"{indent}{ctype} {name}[{sz}];"
    # stack_alloc[T; n]
    m = re.match(r'let (\w+): stack_alloc\[(\w+); (\w+)\]$', line.strip())
    if m:
        name, typ, sz = m.groups()
        ctype = map_type(typ)
        return (f"{indent}{ctype} {name}_stack[{sz} <= COUNT_STACK_MAX ? {sz} : 1]; /* VLA */\n"
                f"{indent}{ctype}* {name} = ({sz} <= COUNT_STACK_MAX) ? {name}_stack\n"
                f"{indent}    : ({ctype}*)calloc({sz}, sizeof({ctype})); /* heap fallback */")
    # let/var x = expr  (no type)
    m = re.match(r'(let|var) (\w+) = (.+)', line.strip())
    if m:
        _, name, expr = m.groups()
        expr = tr_expr(expr)
        return f"{indent}auto {name} = {expr}; /* inferred */"
    return None

def tr_expr(expr):
    """Translate expression-level Logos → C."""
    expr = expr.strip().rstrip(';')
    # wrapping_add / wrapping_mul (C integers wrap naturally)
    expr = re.sub(r'\.wrapping_add\((.+?)\)', r' + (\1)', expr)
    expr = re.sub(r'\.wrapping_mul\((.+?)\)', r' * (\1)', expr)
    # Type casts: x as T
    def cast_repl(m):
        return f"({map_type(m.group(2))})({m.group(1)})"
    expr = re.sub(r'(\w+) as (\w+)', cast_repl, expr)
    # ilog2
    expr = re.sub(r'ilog2\((.+?)\)', r'(int)(log2((double)(\1)))', expr)
    # zero_fill
    expr = re.sub(r'zero_fill\((\w+), (\w+)\)',
                  r'memset(\1, 0, (\2) * sizeof(*\1))', expr)
    # swap(x, y)
    expr = re.sub(r'\bswap\((\w+), (\w+)\)',
                  r'SWAP_VALS(int64_t, \1, \2)', expr)
    # swap_elem(a, i, j)
    expr = re.sub(r'swap_elem\((\w+), (\w+), (\w+)\)',
                  r'{ int64_t _t=\1[\2]; \1[\2]=\1[\3]; \1[\3]=_t; }', expr)
    # oracle.seed dereference via pointer
    expr = expr.replace('oracle.seed', 'oracle->seed')
    # Boolean literals
    expr = expr.replace('true', '1').replace('false', '0')
    return expr

def tr_fn_sig(line):
    """Convert fn / pub fn signature to C."""
    # pub fn name(args) -> RetType
    m = re.match(r'(pub )?fn (\w+)\(([^)]*)\)(?: -> (.+))? \{', line.strip())
    if not m:
        return None
    pub, name, args, ret = m.groups()
    static = "" if pub else "static "
    cret = map_type(ret.strip()) if ret else "void"
    # Translate argument list
    def tr_arg(a):
        a = a.strip()
        if ':' in a:
            aname, atype = a.split(':', 1)
            return f"{map_type(atype.strip())} {aname.strip()}"
        return a
    cargs = ", ".join(tr_arg(a) for a in args.split(',')) if args.strip() else "void"
    return f"{static}{cret} {name}({cargs}) {{"

def tr_struct(lines, i):
    """Convert struct block to C typedef struct."""
    m = re.match(r'struct (\w+) \{', lines[i].strip())
    if not m:
        return None, i
    name = m.group(1)
    out = [f"typedef struct {name} {{"]
    i += 1
    while i < len(lines) and '}' not in lines[i]:
        field = lines[i].strip().rstrip(',')
        if ':' in field:
            fname, ftype = field.split(':', 1)
            out.append(f"    {map_type(ftype.strip())} {fname.strip()};")
        i += 1
    out.append(f"}} {name};")
    return "\n".join(out), i

def tr_const(line):
    m = re.match(r'const (\w+)\s*:\s*(\w+)\s*=\s*(.+)', line.strip())
    if m:
        name, typ, val = m.groups()
        ctype = map_type(typ)
        val = val.rstrip()
        # Hex constants
        val = val.replace('_', '').replace('0x', '0x')
        if ctype == "uint64_t":
            val = f"UINT64_C({val})"
        return f"static const {ctype} {name} = {val};"
    return None

# ── Main transpilation pass ───────────────────────────────────────────────────

def transpile(source):
    lines = source.splitlines()
    out = [HEADER]
    i = 0
    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()
        indent = raw[:len(raw) - len(raw.lstrip())]

        # Skip empty lines and comments
        if not stripped or stripped.startswith('//'):
            out.append(raw)
            i += 1
            continue

        # struct
        if stripped.startswith('struct '):
            result, i = tr_struct(lines, i)
            if result:
                out.append(result)
                i += 1
                continue

        # const
        c = tr_const(stripped)
        if c:
            out.append(indent + c)
            i += 1
            continue

        # fn / pub fn
        fn_sig = tr_fn_sig(raw)
        if fn_sig:
            out.append(fn_sig)
            i += 1
            continue

        # for range
        fr = tr_for_range(raw, indent)
        if fr:
            out.append(fr)
            i += 1
            continue

        # let / var declaration
        lv = tr_let_var(raw, indent)
        if lv:
            out.append(lv)
            i += 1
            continue

        # loop → while(1)
        if stripped == 'loop {':
            out.append(f"{indent}while (1) {{")
            i += 1
            continue

        # tail TCO: tail (lo, hi, depth) = (expr, expr, expr)
        m = re.match(r'tail \(([^)]+)\) = \(([^)]+)\)', stripped)
        if m:
            names = [n.strip() for n in m.group(1).split(',')]
            vals  = [v.strip() for v in m.group(2).split(',')]
            for n, v in zip(names, vals):
                out.append(f"{indent}{n} = {tr_expr(v)};")
            out.append(f"{indent}continue; /* TCO */")
            i += 1
            continue

        # while / if / else — pass through with expr translation
        for kw in ('while ', 'if ', 'else if ', '} else {'):
            if stripped.startswith(kw):
                # translate expressions in condition
                translated = tr_expr(stripped)
                out.append(indent + translated)
                break
        else:
            # General expression line — translate and emit
            out.append(indent + tr_expr(stripped))

        i += 1

    return "\n".join(out)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: logos_compile.py <source.lg>", file=sys.stderr)
        sys.exit(1)
    with open(sys.argv[1]) as f:
        src = f.read()
    print(transpile(src))
